### ISSUE TITLE
Installing VC_redist old version.

### ISSUE THREAD

**Issue by Hellements** [farag2/Sophia-Script-for-Windows#335]
### Prerequisites

- [ ] Verify that this is not a Windows issue;
- [ ] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [ ] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Hello. I noticed that Sophia script is installing an old VC_redist version when I run it.
The version it's installing is 14.29 and the latest is 14.32 as you can see here: https://download.visualstudio.microsoft.com/download/pr/f359701c-0fda-414e-83c2-31d65ee7f308/4B2947448BF80CC987A440B43A1AA07152B9057915C68930061C74E0B40BA05B/VC_redist.x64.exe
It's not a big problem, but if you can update it will be nice.
Thanks in advance.

**Comment by farag2** [comment]
Hi. Yeah, I know. There is a wrong URL in https://github.com/farag2/Sophia-Script-for-Windows/blob/5318bf9c5574fbd12997aabb85d25db7bc6f8b92/Sophia%20Script/Sophia%20Script%20for%20Windows%2010/Module/Sophia.psm1#L8213

Already fixed in 5.12.14/6.0.14. Actually, they're done. But today I had a cool idea for the script to improve. I may upload here for you the current latest version, if you wish.

**Comment by Hellements** [comment]
Hey friend, don't worry.
I can wait for the next release, no problem. :)
Again, thank you.

**Comment by farag2** [comment]
Fixed in 6.0.14
