### ISSUE TITLE
Changing User subfolders location doesn't update properly. 

### ISSUE THREAD

**Issue by Generic4613** [farag2/Sophia-Script-for-Windows#525]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Following the recent update of the Sophia script that introduced the keyboard input functionality for User Folder selection (Desktop, Music, Downloads, Videos, Pictures), a glitch has been detected. On choosing to 'browse' a particular folder, the system malfunctions. The subsequent options default to 'skip,' eliminating the possibility of determining the folder's path or location.

An oddity also arises in File Explorer where, after browsing to a folder, a ")" is appended at the end of the folder's name. It was further observed that folders for which 'browse' was selected were generated at the root level of the chosen path. For example, if the path was C:/Test/123, the folders were created within C:/Test/, rather than the intended directory.

### Windows Version

Win 11 Pro 22H2 22621.1992

### Sophia Script version

6.5.4

**Comment by farag2** [comment]
I will take a look.

**Comment by farag2** [comment]
What is the function name?

**Comment by farag2** [comment]
I fixed few strings. Please test. Probably, I will need to check the bug remotely on your side.

**Comment by john-ea** [comment]
Here there are still typos in the code ($Browser -> $Browse), due to which the choise of folders does not work:

1. https://github.com/farag2/Sophia-Script-for-Windows/blob/bf920bf64d7a3088a5c92f716602f018e2354af5/src/Sophia_Script_for_Windows_11/Module/Sophia.psm1#L7442
2. https://github.com/farag2/Sophia-Script-for-Windows/blob/bf920bf64d7a3088a5c92f716602f018e2354af5/src/Sophia_Script_for_Windows_11/Module/Sophia.psm1#L7482
3. https://github.com/farag2/Sophia-Script-for-Windows/blob/bf920bf64d7a3088a5c92f716602f018e2354af5/src/Sophia_Script_for_Windows_11/Module/Sophia.psm1#L7522
4. https://github.com/farag2/Sophia-Script-for-Windows/blob/bf920bf64d7a3088a5c92f716602f018e2354af5/src/Sophia_Script_for_Windows_11/Module/Sophia.psm1#L7562
