### ISSUE TITLE
Question: Compatibility with `O&O ShutUp10++`?

### ISSUE THREAD

**Issue by Obegg** [farag2/Sophia-Script-for-Windows#534]
Sophia Script is checking whether Windows was broken by 3rd party harmful tweakers and trojans:
https://github.com/farag2/Sophia-Script-for-Windows/blob/52c5312cdde5fdf202b29a72e33760c5ac675564/src/Sophia_Script_for_Windows_10/Module/Sophia.psm1#L292-L320
I'm asking if [O&O ShutUp10++](https://www.oo-software.com/en/shutup10) is breaking Sophia Script or not.

If not - should I use Sophia Script before or after using [O&O ShutUp10++](https://www.oo-software.com/en/shutup10)?

**Comment by farag2** [comment]
Will check tomorrow. :)

**Comment by farag2** [comment]
I remember about your question. But I still not at home.

**Comment by farag2** [comment]
Hi. I'm back.
Well, despite I do not like apps parasiting on disabling Windows telemetry, it's fully safe to use it with Sophia Script. it just relies on GPO. Nothing new and special. It cannot provide anything unique due to any similar apps rely on Windows API.

Let me know, if you receive any errors.

**Comment by farag2** [comment]
And use it wisely. May the force be with you)

**Comment by farag2** [comment]
>  it could be that if running ShutUp10 afterwards it could enable some features that Sophia Script already disabled.

Configure preset to be sure what you want )

> what is your recommendation about the order of running both

I do not see any differences. it's up to you. 

> The reason I'm asking is because Sophia Script does disable some features

It disables what is marked in preset.

**Comment by farag2** [comment]
> O&O ShutUp

I do not want to integrate a 3rd party app (not created by MS like I have to use their LGPO.exe). Actually, I do not like policies for home users, due to the project wasn't intended to be used on the Enterprise sector. users always forget which policy they applied before and do not understand how to revert changes back. So I like to rely on pure Windows UI features that don't use on policies (if possible) to be easily removed if a user needs that.

> will have everything inside it.

This is a voluntarism. :)

**Comment by farag2** [comment]
> my intent was to get each feature of this app

I do not like apps which rely on GPOs. I try to avoid such features.
