### ISSUE TITLE
Telemetry enabled?

### ISSUE THREAD

**Issue by Obegg** [farag2/Sophia-Script-for-Windows#536]
After clean install and running Sophia Script I noticed that Telemetry is enabled.
```
Group Policy > Computer Configuration > Administrative Templates > Windows Components > Data Collection and Preview Builds > Allow Telemetry
```

The description of Sophia Script is:
![image](https://github.com/farag2/Sophia-Script-for-Windows/assets/13978119/e69ec4f6-1d1e-4ec3-ab1f-5b6de1e37486)
So why doesn't it disable what's supposed to be disabled?

**Comment by farag2** [comment]
https://github.com/farag2/Sophia-Script-for-Windows/blob/8fd992d4da734d549c58e59d3b5ea62a4dca84a8/src/Sophia_Script_for_Windows_11/Sophia.ps1#L801

`RecommendedTroubleshooting -Automatically` enables full telemetry gathering in order to make this function work. You had to configure preset before running! You fear telemetry? What does it do bad? Or you read that it's one of horseman of Apocalypses as every yellow pages sites write?

> Disable OS telemetry

What if to read further? `Disable OS telemetry by purposely uprooting system components`.

Set up Privacy & Telemetry ≠ not only disable telemetry.

**Comment by farag2** [comment]
> Ok, So you blame `RecommendedTroubleshooting -Automatically`, so I tested the following: Edited `.\Sophia.ps1` to use `RecommendedTroubleshooting -Default`
> 
> ```
> Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
> .\Sophia.ps1
> ```
> 
> Even now the result is the same, `Allow Telemetry` is `Enabled`, I want to disable it.

You need to call `DiagnosticDataLevel -Minimal`!

> There is no Never option, and no option to disable those:

Because this feature fully relies in telemetry!

**Comment by farag2** [comment]
`.\Sophia.ps1 "DiagnosticDataLevel -Minimal"`

```
.\Functions.ps1
Sophia -Functions "DiagnosticDataLevel -Minimal"
```

https://github.com/farag2/Sophia-Script-for-Windows?tab=readme-ov-file#how-to-run-the-specific-functions
