### ISSUE TITLE
Terminal closes upon selecting 'Yes' indicated Sophia.ps1 file had been modified

### ISSUE THREAD

**Issue by swiftyseven-dev** [farag2/Sophia-Script-for-Windows#546]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

1. Download via Powershell (per instructions).
2. Modify the [Sophia.ps1](https://github.com/farag2/Sophia-Script-for-Windows/files/13469883/Sophia.ps1.zip) file (compressed, attached).
3. Open elevated Powershell instance.
4. Set execution policy per instructions.
5. Navigate to parent folder and execute script file `./Sophia.ps1`
6. Script begins to execute, asking if the contents have been modified and to use arrow keys to select either 'Yes' or 'No'.
7. Select 'Yes'.
8. Terminal instance immediately closes.

I assumed possibly it was different than when I ran it on my Windows 10 machine, thinking maybe it was doing stuff in the background, but after waiting about 15 minutes and receiving no prompts and no progress, I restarted the computer and tried again.

### Windows Version

Windows 11 Pro 23H2 22631.2715

### Sophia Script version

6.5.7

**Comment by siberianspot** [comment]
Running the script in Windows Terminal in PowerShell 7.4 session (both installed from Windows Store) i’ve got the same issue.
If you’re enable creating a recovery point by script, just make recovery point by yourself before run the script and comment this option.
If you’re using VPN connection as internet gateway and it’s not utilizing appropriate Windows features (but maybe i’m wrong and using Windows VPN settings will have same results — i cannot test it) prepare yourself to “No internet connection” messages and failed options that depends on connection. At least this was a my case. And even after i’ve got the default connection there was at least one “No connection” script message, although I don’t think it was a script issue, but the consequences of the censorship of the dictatorial regime under which I live.
And the last one. If you’ve localized Windows then do not enable file logging — in my case script always fails with C-error about “no pipes on both ends”. And you should open-save in UTF-8 with BOM all scripts and modules in Sophia directory tree (2 or 3 of them have UTF-8 w/o BOM and this can be an issue too). You can do that with VSCode. But maybe it will not enough as you could get notification window from Sophia created tasks with message full of unreadable symbols. To fix that go in Windows Scheduled Tasks control and navigate to Sophia directory to find out where the task files is (because I don’t remember and on iphone now, but it’s something about %WINDOWS%\System32\Tasks\Sophia). Look at that directory and open-save as UTF-8 with BOM all *.ps1 and [maybe] *.vcs files. Now the messages will be alright.

**Comment by farag2** [comment]
![изображение](https://github.com/farag2/Sophia-Script-for-Windows/assets/10544660/42d4094b-2e28-4d2d-91c1-1720f8ee758a)

Hello! This is a Terminal bug. It was already fixed by MS few days ago. Please temporarily use Windows Terminal Preview.

https://github.com/microsoft/terminal/issues/16212

**Comment by farag2** [comment]
For me works without any issues on the latest preview!

**Comment by farag2** [comment]
> it’s not utilizing appropriate Windows features

The script fully relies on the Windows Internet connection check via resolving DNS. Fully like Windows does. So if the script says that there's no conenection, that means that you have a globe icon in the notification area))

**Comment by swiftyseven-dev** [comment]
> For me works without any issues on the latest preview!

Same here - much appreciated!

![](https://media.giphy.com/media/BYoRqTmcgzHcL9TCy1/giphy.gif)
