### ISSUE TITLE
[Question] harmful tweakers = winutil

### ISSUE THREAD

**Issue by Obegg** [farag2/Sophia-Script-for-Windows#550]
Latest commit https://github.com/farag2/Sophia-Script-for-Windows/commit/e0f2b1f02592e35fc5083b81c7037de78c322bce added [winutil](https://github.com/ChrisTitusTech/winutil) to the list of harmful tweakers, my question is why or what exactly is harmful (maybe I can talk to the developer and change it?)

**Comment by farag2** [comment]
Hi. All because the so-called tweaker provides a feature to break Windows by removing (not disabling) Defender as a folder. Such stuff provides only by trojans. By this act he like says to his audience that this is normal, everyone can break Windows to make it vulnerable to all kinds of viruses (especially to low-skilled users). This is evil. For that winutil was marked as trojan and every Sophia Script user will be notified if they ran such things before because I'm tired of broken Windows after such tweakers which has the only thing to convey to users is that Windows is bad, it has to be "fixed", "optimized" and so on. But the only thing such tweakers provides is to remove poor Defender as TrustedInstaller and allow user to download a god forgotten app from its GUI.

**Comment by farag2** [comment]
https://github.com/ChrisTitusTech/winutil/blob/a2b12ae4b0bb8f58c9def3865cc8dff64279fbba/winutil.ps1#L2664

Such "scripts" is a cancer and should be blocked on any platform, regardless of being open-source or not.

**Comment by farag2** [comment]
Normal apps won't provide or even notice about such things. Of course if a developer respects his audience (he doesn't).

> While I do agree such feature should not exist, it doesn't mean the entirely of [winutil](https://github.com/ChrisTitusTech/winutil) is harmful.

Agree until he will remove Defender installation. Until that, the is marked as a trojan.

**Comment by farag2** [comment]
I know his position regarding WU. I think that good apps do not provide harmful features regardless what's behind of them. Disabling WU is an evil.

I will stand my ground. :) Younneed to convince him, not me. At least I'm not willing to break users Windows. :cat:

**Comment by farag2** [comment]
I didn't make a whole code audit of his project, but that was enough for me to add him. So for now, yes, these are 2 only issues.

**Comment by NicholasFlamy** [comment]
Why are you being such a jerk? Your scripts are now a Trojan with stuff like connectivity checks and this stuff.

**Comment by farag2** [comment]
Where's my scripts are trojan? Sophia warns if you broke your Windows with real trojans like stuff you mentioned. Lol

**Comment by NicholasFlamy** [comment]
> Where is my scripts are a trojan? Sophia warns if you broke your Windows with real trojans like stuff you mentioned. Lol

I don't mean to be too much of a jerk in response, but I'll probably come off as a jerk.
First off, thank you for your response. I'm glad you're willing to respond.

The defintion of a trojan is something that appears to do one thing but secretly does another thing. While I'm very happy that you comment your code in your scripts, I don't see it mentioned in your features list on GitHub that you check the OS for other (technically competing) software and require internet to do anything (and require downloading the latest version of the script).

Winutil clearly identifies the feature allowing you to disable/remove Windows Defender. That is not a trojan. Maybe you could call it an unsafe, insecure feature if you really don't like it.

**Comment by farag2** [comment]
> I don't see it mentioned in your features list on GitHub that you check the OS for other (technically competing) software and require internet to do anything (and require downloading the latest version of the script).

Because generally users do not run any harmful tweakers.

> That is not a trojan

It is because code written within ChatGPT by Chris makes Windows unstable. Only nonpro allows users to disable a built-in AV and WU making Windows vulnerable instead of explaing that Defender is not an evil and installing WU makes your OS safe. That's why Chris is a nonpro writing his code within ChatGPT, knowing nothing about Windows internals. and just placing his smiling face in another video how he likes Linux.
